# Generated by Django 4.0.4 on 2022-04-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state_zip', models.CharField(max_length=15)),
                ('price', models.IntegerField(default=0)),
                ('bedrooms', models.FloatField(default=0)),
                ('bathrooms', models.FloatField(default=0)),
                ('sqft_living', models.IntegerField(default=0)),
                ('sqft_lot', models.IntegerField(default=0)),
                ('floors', models.FloatField(default=0)),
                ('waterfront', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('condition', models.IntegerField(default=0)),
                ('sqft_above', models.IntegerField(default=0)),
                ('sqft_basement', models.IntegerField(default=0)),
                ('yr_built', models.IntegerField(default=0)),
                ('yr_renovated', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_country', to='homes.country')),
            ],
        ),
    ]
