# Generated by Django 4.0.4 on 2022-04-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
